trigger:
- main

pool: Dexter

steps:
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: 'backend/Dockerfile'
    buildContext: '$(Build.ArtifactStagingDirectory)'
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: 'frontend/Dockerfile'
    buildContext: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: Send Artifact
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'Dexter'