trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Dexter
    steps:
    - task: Docker@2
      displayName: Build backend
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/backend/Dockerfile'
        buildContext: '$(Build.ArtifactStagingDirectory)'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build frontend
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/frontend/Dockerfile'
        buildContext: '$(Build.ArtifactStagingDirectory)'
        tags: |
          $(tag)
    - task: PublishBuildArtifacts@1
      displayName: Send Artifact
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'Dexter'
