trigger:
- main

pool: Dexter

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.sln'
  
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: true
    projects: '**/*.sln'
    arguments: '-r linux-x64 --output $(Build.ArtifactStagingDirectory) --self-contained'

- task: PublishBuildArtifacts@1
  displayName: Send Artifact
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'Dexter'